(if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
(if (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(if (fboundp 'menu-bar-mode) (menu-bar-mode -1))
(set-default-font "Liberation Mono 11")
(setq inhibit-startup-screen t)
(setq initial-frame-alist nil)
;; (setq (menu-bar-mode nil))
;; (setq (scroll-bar-mode nil))
;; (setq (tool-bar-mode nil))
(setq c-default-style "linux")
(setq make-backup-files nil) ;; stop making those annoying file~ files)
(global-hl-line-mode 1)
(global-linum-mode 1)
(set-face-background 'hl-line "light grey")
(setq auto-save-timeout 3)
(setq auto-save-interval 100)
(setq org-log-done t)
