(if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
(if (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(if (fboundp 'menu-bar-mode) (menu-bar-mode -1))
(setq inhibit-startup-screen t)
(setq initial-frame-alist nil)
;; (setq (menu-bar-mode nil))
;; (setq (scroll-bar-mode nil))
;; (setq (tool-bar-mode nil))
(setq c-default-style "linux")
(setq make-backup-files nil) ;; stop making those annoying file~ files