(if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
(if (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(if (fboundp 'menu-bar-mode) (menu-bar-mode -1))
(set-default-font "Liberation Mono 11")
(setq inhibit-startup-screen t)
(setq initial-frame-alist nil)
;; (setq (menu-bar-mode nil))
;; (setq (scroll-bar-mode nil))
;; (setq (tool-bar-mode nil))
(setq c-default-style "linux")
(setq make-backup-files nil) ;; stop making those annoying file~ files)
(global-hl-line-mode 1)
(global-linum-mode 1)
(set-face-background 'hl-line "light grey")
(setq auto-save-timeout 3)
(setq auto-save-interval 100)
(setq org-log-done t)

;; Use tabs instead of spaces. Messes with styles, but that's what our other editors are doing.
(setq indent-tabs-mode t)
(setq-default indent-tabs-mode t)
(global-set-key (kbd "TAB") 'self-insert-command)
(setq default-tab-width 8)
(setq tab-width 8)
(setq c-basic-indent 8)
